/* =========================================================
   SAG Proyectos TI — Datos y Catálogos Simulados
   ========================================================= */

const initialData = {
    catalogos: {
        sistemas: ["SIAG", "Portal Trámites", "SIPEC", "Gestión Documental", "SIGA", "App Fiscalización"],
        divisiones: ["División TI", "Protección Agrícola", "Protección Pecuaria", "Fronteras", "Administración"],
        coordinadores: ["Juan Pérez", "María Silva", "Carlos Torres", "Ana Martínez", "Roberto Gómez"],
        unidadesUsuarias: ["DPF", "DPP", "DPA", "RRHH", "Finanzas", "Jurídica"],
        proveedores: ["Entel", "Sonda", "Kibernum", "Soho", "Interno"],
        estados: ["Planificado", "En curso", "Pausado", "Cancelado", "Finalizado"],
        categorias: ["Nuevo Desarrollo", "Mejora", "Mantención Evolutiva"],
        tiposDesarrollo: ["Interno", "Externo", "Mixto"]
    },
    
    proyectos: [
        {
            id: "prj-001",
            nombre: "Sistema de Trazabilidad Animal (SIAG 2.0)",
            sistema: "SIAG",
            descripcion: "Migración a nueva arquitectura cloud y modernización de interfaces para trazabilidad bovina.",
            categoria: "Mejora",
            division_departamento: "División TI",
            unidad_usuaria: "DPP",
            responsable_usuario: "Pedro Campos",
            coordinador: "María Silva",
            tipo_proyecto: "Mejora",
            tipo_desarrollo: "Mixto",
            proveedor: "Entel",
            fecha_inicio_planificada: "2026-01-15",
            fecha_fin_planificada: "2026-08-30",
            fecha_inicio_real: "2026-01-20",
            fecha_fin_real: "",
            inicio_contrato: "2026-01-01",
            fin_contrato: "2026-12-31",
            estado: "En curso",
            prioridad: "Alta",
            criticidad: "Alta",
            porcentaje_avance: 45,
            semaforo: "Amarillo",
            fecha_ultima_actualizacion: "2026-04-01"
        },
        {
            id: "prj-002",
            nombre: "Portal Único de Trámites SAG",
            sistema: "Portal Trámites",
            descripcion: "Ventanilla única para todos los trámites ciudadanos del SAG con integración a Clave Única.",
            categoria: "Nuevo Desarrollo",
            division_departamento: "División TI",
            unidad_usuaria: "Jurídica",
            responsable_usuario: "Laura Muñoz",
            coordinador: "Juan Pérez",
            tipo_proyecto: "Nuevo",
            tipo_desarrollo: "Externo",
            proveedor: "Sonda",
            fecha_inicio_planificada: "2025-10-01",
            fecha_fin_planificada: "2026-06-30",
            fecha_inicio_real: "2025-10-05",
            fecha_fin_real: "",
            inicio_contrato: "2025-09-15",
            fin_contrato: "2026-09-15",
            estado: "En curso",
            prioridad: "Alta",
            criticidad: "Media",
            porcentaje_avance: 70,
            semaforo: "Verde",
            fecha_ultima_actualizacion: "2026-04-05"
        },
        {
            id: "prj-003",
            nombre: "App Móvil Inspección Fronteras",
            sistema: "App Fiscalización",
            descripcion: "Aplicación offline-first para inspectores en pasos fronterizos.",
            categoria: "Nuevo Desarrollo",
            division_departamento: "División TI",
            unidad_usuaria: "Fronteras",
            responsable_usuario: "Diego Ruiz",
            coordinador: "Carlos Torres",
            tipo_proyecto: "Nuevo",
            tipo_desarrollo: "Interno",
            proveedor: "Interno",
            fecha_inicio_planificada: "2026-03-01",
            fecha_fin_planificada: "2026-09-15",
            fecha_inicio_real: "2026-03-10",
            fecha_fin_real: "",
            inicio_contrato: "",
            fin_contrato: "",
            estado: "En curso",
            prioridad: "Media",
            criticidad: "Media",
            porcentaje_avance: 15,
            semaforo: "Rojo",
            fecha_ultima_actualizacion: "2026-03-25"
        },
        {
            id: "prj-004",
            nombre: "Actualización Motor Reglas SIPEC",
            sistema: "SIPEC",
            descripcion: "Ajuste normativo según nueva circular DPA 2026.",
            categoria: "Mantención Evolutiva",
            division_departamento: "División TI",
            unidad_usuaria: "DPA",
            responsable_usuario: "Elena Castro",
            coordinador: "Ana Martínez",
            tipo_proyecto: "Correctivo",
            tipo_desarrollo: "Interno",
            proveedor: "Interno",
            fecha_inicio_planificada: "2026-05-01",
            fecha_fin_planificada: "2026-07-30",
            fecha_inicio_real: "",
            fecha_fin_real: "",
            inicio_contrato: "",
            fin_contrato: "",
            estado: "Planificado",
            prioridad: "Alta",
            criticidad: "Alta",
            porcentaje_avance: 0,
            semaforo: "Verde",
            fecha_ultima_actualizacion: "2026-04-06"
        },
        {
            id: "prj-005",
            nombre: "Migración ECM (Gestión Documental)",
            sistema: "Gestión Documental",
            descripcion: "Paso a nueva plataforma documental con firma electrónica avanzada.",
            categoria: "Mejora",
            division_departamento: "División TI",
            unidad_usuaria: "Administración",
            responsable_usuario: "Ricardo Vega",
            coordinador: "Roberto Gómez",
            tipo_proyecto: "Mejora",
            tipo_desarrollo: "Externo",
            proveedor: "Kibernum",
            fecha_inicio_planificada: "2025-06-01",
            fecha_fin_planificada: "2026-02-28",
            fecha_inicio_real: "2025-06-15",
            fecha_fin_real: "2026-03-15",
            inicio_contrato: "2025-05-01",
            fin_contrato: "2026-04-30",
            estado: "Finalizado",
            prioridad: "Media",
            criticidad: "Media",
            porcentaje_avance: 100,
            semaforo: "Verde",
            fecha_ultima_actualizacion: "2026-03-20"
        }
    ],

    seguimientos: [
        {
            id: "seg-001",
            proyecto_id: "prj-001",
            fecha_reporte: "2026-04-01",
            semana: "2026-W14",
            avance_semanal: "5%",
            avance_acumulado: "45%",
            actividades_realizadas: "- Análisis de requerimientos DPA\n- Pruebas concepto API cloud",
            actividades_proximas: "- Cerrar diseño técnico\n- Inicio desarrollo módulo 1",
            problemas: "Falta definición formato reportes",
            riesgos: "Retraso proveedor Entel",
            bloqueos: "Ninguno",
            acuerdos: "Reunión técnica el viernes",
            responsable: "María Silva"
        },
        {
            id: "seg-002",
            proyecto_id: "prj-002",
            fecha_reporte: "2026-04-05",
            semana: "2026-W14",
            avance_semanal: "8%",
            avance_acumulado: "70%",
            actividades_realizadas: "Paso a UAT exitoso, integración Clave Única OK",
            actividades_proximas: "Fijar fecha paso a prod",
            problemas: "",
            riesgos: "",
            bloqueos: "",
            acuerdos: "",
            responsable: "Juan Pérez"
        }
    ],

    riesgos: [
        {
            id: "rsk-001",
            proyecto_id: "prj-001",
            tipo: "Riesgo",
            descripcion: "Inestabilidad en ambiente cloud para base de datos",
            impacto: "Alto",
            probabilidad: "Alta",
            severidad: "Alta",
            responsable: "Equipo Infraestructura",
            plan_accion: "Solicitar ampliación recursos cloud",
            estado: "Abierto",
            fecha_compromiso: "2026-04-15"
        },
        {
            id: "rsk-002",
            proyecto_id: "prj-003",
            tipo: "Bloqueo",
            descripcion: "Renuncia desarrollador principal móvil",
            impacto: "Alto",
            probabilidad: "-",
            severidad: "Alta",
            responsable: "Carlos Torres",
            plan_accion: "Contratación express / reasignar recursos",
            estado: "En gestión",
            fecha_compromiso: "2026-04-20"
        }
    ],

    hitos: [
        {
            id: "ht-001",
            proyecto_id: "prj-001",
            nombre: "Levantamiento Requerimientos",
            fecha_planificada: "2026-02-15",
            fecha_real: "2026-02-20",
            estado: "Completado",
            peso_porcentual: 20
        },
        {
            id: "ht-002",
            proyecto_id: "prj-001",
            nombre: "Diseño Arquitectura",
            fecha_planificada: "2026-03-30",
            fecha_real: "2026-04-02",
            estado: "Completado",
            peso_porcentual: 25
        },
        {
            id: "ht-003",
            proyecto_id: "prj-001",
            nombre: "Paso a QA",
            fecha_planificada: "2026-07-01",
            fecha_real: "",
            estado: "Pendiente",
            peso_porcentual: 40
        }
    ]
};
